# Generated by Django 3.2.23 on 2024-02-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20240203_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
