# Generated by Django 3.2.23 on 2024-02-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderlineitem_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
