# Generated by Django 3.2.23 on 2024-01-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointeShoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('size', models.CharField(max_length=50)),
                ('width', models.CharField(choices=[('x', 'X'), ('xx', 'XX'), ('xxx', 'XXX'), ('xxxx', 'XXXX'), ('xxxxx', 'XXXXX')], max_length=5)),
                ('shank', models.CharField(choices=[('ss', 'SS'), ('s', 'S'), ('m', 'M'), ('h', 'H'), ('sh', 'SH')], max_length=2)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], max_length=50)),
                ('arch', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('link', models.URLField(blank=True, null=True)),
                ('ribbon', models.CharField(choices=[('beige', 'Ribbon Beige'), ('pink', 'Ribbon Pink')], max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointeShoeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='PointeShoeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pointeshoebrand')),
                ('pointe_shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pointeshoe')),
            ],
        ),
        migrations.AddField(
            model_name='pointeshoe',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.pointeshoebrand'),
        ),
    ]
