# Generated by Django 3.2.23 on 2024-01-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='pointeshoe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pointeshoe',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='pointeshoe',
            name='size',
        ),
        migrations.AddField(
            model_name='pointeshoe',
            name='available_sizes',
            field=models.CharField(choices=[('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44')], default='33', max_length=50),
        ),
        migrations.AddField(
            model_name='pointeshoe',
            name='available_widths',
            field=models.CharField(choices=[('x', 'X'), ('xx', 'XX'), ('xxx', 'XXX'), ('xxxx', 'XXXX'), ('xxxxx', 'XXXXX')], default='x', max_length=5),
        ),
        migrations.AddField(
            model_name='pointeshoe',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointeshoe',
            name='feature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointeshoeproduct',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
