# Generated by Django 3.2.23 on 2024-01-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20240115_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointeshoeproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pointeshoeproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
