# Generated by Django 3.2.23 on 2024-01-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_pointeshoeproduct_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointeshoe',
            name='color',
            field=models.CharField(choices=[('satin_pink', 'Satin Pink'), ('satin_beige', 'Satin Beige')], max_length=50),
        ),
    ]
